### ISSUE TITLE
Target is still executed if yaml condition failed

### ISSUE THREAD

**Issue by olblak** [olblak/updatecli#116]
**Describe the bug**

Target is still executed if yaml condition failed

**To Reproduce**

**Expected behavior**

**Version (please complete the following information):**
 - OS: linux
 - Version: v0.0.22, v0.0.23

**Comment by olblak** [comment]
Fixed in this [commit](https://github.com/olblak/updatecli/commit/2ff2e6e20db940bd37e5c08b1f1f30b254e4b913) which didn't follow the PR workflow because of a mistake on my side

**Comment by jetersen** [comment]
🤷‍♂️ You can still use `fixes` in a commit message to close issues
