### ISSUE TITLE
No content in commits 😱

### ISSUE THREAD

**Issue by jetersen** [olblak/updatecli#75]
**Describe the bug**

Reverting changes locally and running updatecli again creates a new commit and is pushed to the branch even there is no diff in the two commits.
It means I cannot use rebase and in these cases I don't want to use squash either 😅

![image](https://user-images.githubusercontent.com/1661688/87778210-20f07580-c82b-11ea-9939-d8b9525b54ef.png)

WAIT what? The PR has no content using 0.0.15. This seems to go for all PRs.
![image](https://user-images.githubusercontent.com/1661688/87778740-f05d0b80-c82b-11ea-95d3-8ea4a210e476.png)

Also why are changes being applied to local files in your git repo? Seems counter intuitive when testing our new updatecli files. I think something foobar is going on. The file changes and commits are not happening in the right folders.
![image](https://user-images.githubusercontent.com/1661688/87778489-94928280-c82b-11ea-912f-5ae90f74f6da.png)

**Expected behavior**
Only one commit per updated version and PR actually have content.

**Info**
```
$ updatecli version

VERSION


Application:    v0.0.15
Golang     :    1.14.2 linux/amd64
Build Time :    Fri, 17 Jul 2020 11:46:45 +0200
```

**Comment by jetersen** [comment]
The code should properly error on empty commits 😅

**Comment by olblak** [comment]
Oups This is definitely not wanted and  I guess I did something wrong while testing the changes, let me look at it

**Comment by jetersen** [comment]
No worries 😅
I love the tool and what it does.

Sorry for not contributing more with code 🥵

**Comment by olblak** [comment]
This should be solved now, I am still not certain about the best way to not commit empty commits and won't have the time to work on that today  but at least the tool is working again.

**Comment by jetersen** [comment]
I may be able to look into erroring on empty commits :)

Thanks for fixing the issue!

**Comment by olblak** [comment]
Awesome, just in case I am using this git library  [go-git](https://github.com/go-git/go-git/)
